-- CodeMetrix: store authorized LeetCode submissions captured by the student-side extension.
create table if not exists public.leetcode_submissions (
    id bigint generated by default as identity primary key,
    register_number text not null,
    leetcode_username text not null,
    submission_id text,
    problem_title text,
    problem_slug text,
    language text,
    status text,
    submitted_at timestamptz not null default now(),
    source_code text not null,
    source text not null default 'codemetrix-extension',
    created_at timestamptz not null default now()
);

create index if not exists idx_lc_submissions_register
    on public.leetcode_submissions(register_number);
create index if not exists idx_lc_submissions_username
    on public.leetcode_submissions(leetcode_username);
create index if not exists idx_lc_submissions_time
    on public.leetcode_submissions(submitted_at desc);

alter table public.leetcode_submissions enable row level security;

-- No public INSERT/SELECT policy is created.
-- The Render API writes using the Supabase service-role key.
