-- =====================================================================
-- CODEMETRIX LEETCODE SYNC - SUPABASE DATABASE MIGRATION
-- With Anti-Cheating, Keystroke Forensics & Plagiarism Detection
-- =====================================================================

begin;

create table if not exists public.student_leetcode_submissions (
  id bigint generated by default as identity primary key,
  register_number text not null,
  leetcode_username text not null,
  problem_title text not null,
  problem_slug text not null,
  problem_difficulty text default 'Medium' check (problem_difficulty in ('Easy', 'Medium', 'Hard', 'Unknown')),
  language text not null,
  submission_status text not null default 'Accepted',
  runtime_ms integer default 0,
  runtime_percentile numeric default 0,
  memory_mb numeric default 0,
  memory_percentile numeric default 0,
  source_code text not null,
  
  -- Anti-Cheating & Forensics Telemetry
  keystrokes_count integer default 0,
  keystroke_ratio numeric default 0,
  is_pasted boolean default false,
  paste_count integer default 0,
  time_spent_seconds integer default 0,
  tab_switch_count integer default 0,
  has_prompt_comments boolean default false,
  ai_comment_flags text[] default '{}',
  plagiarism_risk_score integer default 0,
  plagiarism_verdict text default 'CLEAN' check (plagiarism_verdict in ('CLEAN', 'LOW_RISK', 'SUSPICIOUS', 'FLAGGED')),
  peer_similarity_pct numeric default 0,
  
  notes text,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint uq_student_submission unique (register_number, problem_slug, submitted_at)
);

-- Ensure columns exist if table already existed
alter table public.student_leetcode_submissions add column if not exists keystrokes_count integer default 0;
alter table public.student_leetcode_submissions add column if not exists keystroke_ratio numeric default 0;
alter table public.student_leetcode_submissions add column if not exists is_pasted boolean default false;
alter table public.student_leetcode_submissions add column if not exists paste_count integer default 0;
alter table public.student_leetcode_submissions add column if not exists time_spent_seconds integer default 0;
alter table public.student_leetcode_submissions add column if not exists tab_switch_count integer default 0;
alter table public.student_leetcode_submissions add column if not exists has_prompt_comments boolean default false;
alter table public.student_leetcode_submissions add column if not exists ai_comment_flags text[] default '{}';
alter table public.student_leetcode_submissions add column if not exists plagiarism_risk_score integer default 0;
alter table public.student_leetcode_submissions add column if not exists plagiarism_verdict text default 'CLEAN';
alter table public.student_leetcode_submissions add column if not exists peer_similarity_pct numeric default 0;

-- Indexes for lightning-fast lookups and anti-cheat filtering
create index if not exists idx_submissions_register_number on public.student_leetcode_submissions(register_number);
create index if not exists idx_submissions_submitted_at on public.student_leetcode_submissions(submitted_at desc);
create index if not exists idx_submissions_problem_slug on public.student_leetcode_submissions(problem_slug);
create index if not exists idx_submissions_language on public.student_leetcode_submissions(language);
create index if not exists idx_submissions_plagiarism_risk on public.student_leetcode_submissions(plagiarism_risk_score desc);
create index if not exists idx_submissions_plagiarism_verdict on public.student_leetcode_submissions(plagiarism_verdict);

-- Enable Row Level Security
alter table public.student_leetcode_submissions enable row level security;

-- Remove old policies if any
drop policy if exists "Allow public and extension to insert submissions" on public.student_leetcode_submissions;
drop policy if exists "Allow public and authenticated to read submissions" on public.student_leetcode_submissions;
drop policy if exists "Allow admins full access to submissions" on public.student_leetcode_submissions;

-- 1. Read Policy: Anyone can read submissions on the dashboard
create policy "Allow public and authenticated to read submissions"
on public.student_leetcode_submissions
for select
to anon, authenticated
using (true);

-- 2. Insert Policy: Extension can insert solved submissions with forensics
create policy "Allow public and extension to insert submissions"
on public.student_leetcode_submissions
for insert
to anon, authenticated
with check (
  length(trim(register_number)) > 0 and
  length(trim(problem_title)) > 0 and
  length(trim(source_code)) > 0
);

-- 3. Admin Full Management Policy
create policy "Allow admins full access to submissions"
on public.student_leetcode_submissions
for all
to authenticated
using (
  coalesce((select (auth.jwt() ->> 'role') = 'authenticated'), false)
);

-- Function to get latest student submission stats
create or replace function public.get_student_solution_history(p_register_number text, p_limit int default 50)
returns setof public.student_leetcode_submissions
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.student_leetcode_submissions
  where register_number = p_register_number
  order by submitted_at desc
  limit p_limit;
$$;

grant execute on function public.get_student_solution_history(text, int) to anon, authenticated;

commit;

-- Verification query:
select count(*) as total_stored_submissions from public.student_leetcode_submissions;
