-- =====================================================================
-- CODEMETRIX LEETCODE SYNC - EXTENSION STATE & BYPASS DETECTION
-- Run once in Supabase SQL Editor.
-- =====================================================================

-- 1. Ensure table exists
CREATE TABLE IF NOT EXISTS public.extension_installed_students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  register_number TEXT NOT NULL,
  student_email TEXT,
  student_name TEXT NOT NULL,
  section TEXT DEFAULT 'ECE',
  leetcode_username TEXT,
  extension_version TEXT DEFAULT '1.0.0',
  auto_sync_enabled BOOLEAN DEFAULT true,
  installed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_active_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Ensure all columns exist
ALTER TABLE public.extension_installed_students 
  ADD COLUMN IF NOT EXISTS student_email TEXT,
  ADD COLUMN IF NOT EXISTS auto_sync_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS extension_version TEXT DEFAULT '1.0.0',
  ADD COLUMN IF NOT EXISTS installed_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- 3. Unique Constraints (1 Student = 1 Extension)
ALTER TABLE public.extension_installed_students DROP CONSTRAINT IF EXISTS uq_ext_inst_reg;
ALTER TABLE public.extension_installed_students DROP CONSTRAINT IF EXISTS uq_ext_inst_email;
ALTER TABLE public.extension_installed_students ADD CONSTRAINT uq_ext_inst_reg UNIQUE (register_number);

-- 4. Indexes for fast heartbeat queries & status audits
CREATE INDEX IF NOT EXISTS idx_ext_inst_reg ON public.extension_installed_students(register_number);
CREATE INDEX IF NOT EXISTS idx_ext_inst_email ON public.extension_installed_students(student_email);
CREATE INDEX IF NOT EXISTS idx_ext_inst_auto_sync ON public.extension_installed_students(auto_sync_enabled);
CREATE INDEX IF NOT EXISTS idx_ext_inst_last_active ON public.extension_installed_students(last_active_at DESC);

-- 5. RLS Policies (Allow extension to register & send heartbeats)
ALTER TABLE public.extension_installed_students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public to read extension installs" ON public.extension_installed_students;
DROP POLICY IF EXISTS "Allow extension to insert installs" ON public.extension_installed_students;
DROP POLICY IF EXISTS "Allow extension to update installs" ON public.extension_installed_students;

CREATE POLICY "Allow public to read extension installs"
ON public.extension_installed_students FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow extension to insert installs"
ON public.extension_installed_students FOR INSERT TO anon, authenticated
WITH CHECK (length(trim(register_number)) > 0);

CREATE POLICY "Allow extension to update installs"
ON public.extension_installed_students FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

-- 6. Helpful Faculty View: extension_status_overview
-- Shows live extension health, last ping, and whether auto-sync is enabled
CREATE OR REPLACE VIEW public.extension_status_overview AS
SELECT 
  s.register_number,
  s.student_name,
  s.section,
  s.leetcode_username,
  e.student_email,
  e.extension_version,
  CASE 
    WHEN e.register_number IS NULL THEN 'NOT_INSTALLED'
    WHEN e.auto_sync_enabled = false THEN 'TURNED_OFF'
    WHEN e.last_active_at < (now() - interval '7 days') THEN 'INACTIVE_7D'
    ELSE 'ACTIVE'
  END AS extension_state,
  COALESCE(e.auto_sync_enabled, false) AS auto_sync_enabled,
  e.installed_at,
  e.last_active_at,
  COALESCE(sub_stats.total_synced_solutions, 0) AS total_synced_solutions,
  COALESCE(sub_stats.flagged_solutions, 0) AS flagged_solutions
FROM public.students s
LEFT JOIN public.extension_installed_students e 
  ON s.register_number = e.register_number
LEFT JOIN (
  SELECT 
    register_number,
    COUNT(*) AS total_synced_solutions,
    COUNT(*) FILTER (WHERE plagiarism_verdict IN ('FLAGGED', 'SUSPICIOUS')) AS flagged_solutions
  FROM public.student_leetcode_submissions
  GROUP BY register_number
) sub_stats 
  ON s.register_number = sub_stats.register_number
ORDER BY s.section, s.register_number;

-- 7. Grant permissions for view
GRANT SELECT ON public.extension_status_overview TO anon, authenticated;
