-- ================================================================
-- ECE CodeMetrix - LeetCode submission-code integration
-- GitHub Pages + Supabase Edge Function
-- Run once in Supabase SQL Editor.
-- ================================================================

begin;

-- Keep extension credentials OUT of public.students because the frontend may read that table.
create table if not exists public.student_extension_tokens (
  register_number text primary key,
  extension_token text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Create one private token for every current student.
insert into public.student_extension_tokens (register_number, extension_token)
select s.register_number, encode(gen_random_bytes(24), 'hex')
from public.students s
where btrim(coalesce(s.register_number, '')) <> ''
on conflict (register_number) do nothing;

-- Do not allow browser clients to read the pairing tokens.
alter table public.student_extension_tokens enable row level security;
revoke all on public.student_extension_tokens from anon, authenticated;

create table if not exists public.leetcode_submissions (
  id bigint generated by default as identity primary key,
  register_number text not null,
  leetcode_username text not null,
  submission_id text not null,
  problem_title text,
  problem_slug text,
  language text,
  status text,
  submitted_at timestamptz not null,
  source_code text not null,
  source text not null default 'codemetrix-extension',
  created_at timestamptz not null default now(),
  unique (register_number, submission_id)
);

create index if not exists idx_leetcode_submissions_register
  on public.leetcode_submissions(register_number);
create index if not exists idx_leetcode_submissions_username
  on public.leetcode_submissions(leetcode_username);
create index if not exists idx_leetcode_submissions_time
  on public.leetcode_submissions(submitted_at desc);

-- Source code is written only by the Edge Function using the service-role key.
alter table public.leetcode_submissions enable row level security;
revoke all on public.leetcode_submissions from anon, authenticated;

commit;

-- TEST: after running this SQL, execute this query for the student you are testing.
-- Never publish the returned token in the website/frontend.
-- select s.register_number, s.student_name, s.leetcode_username, t.extension_token
-- from public.students s
-- join public.student_extension_tokens t using (register_number)
-- where s.register_number = '922525106255';
