-- ============================================================
-- CODEMETRIX GITHUB TRACKER V1
-- Run ONCE in Supabase SQL Editor.
-- ============================================================

-- 1) Attach an optional GitHub username to each existing student.
alter table public.students
  add column if not exists github_username text;

alter table public.students
  add column if not exists github_profile_url text;

-- Optional GitHub usernames must be unique when present.
create unique index if not exists students_github_username_unique
on public.students (lower(github_username))
where github_username is not null
  and btrim(github_username) <> '';

-- 2) Current GitHub metrics.
create table if not exists public.github_performance_current (
  register_number text primary key
    references public.students(register_number)
    on update cascade
    on delete cascade,

  section text not null,
  student_name text not null,
  github_username text,

  contributions_today integer not null default 0 check (contributions_today >= 0),
  contributions_7_days integer not null default 0 check (contributions_7_days >= 0),
  contributions_14_days integer not null default 0 check (contributions_14_days >= 0),
  contributions_30_days integer not null default 0 check (contributions_30_days >= 0),

  commits_today integer not null default 0 check (commits_today >= 0),
  commits_7_days integer not null default 0 check (commits_7_days >= 0),
  commits_14_days integer not null default 0 check (commits_14_days >= 0),
  commits_30_days integer not null default 0 check (commits_30_days >= 0),

  repositories_total integer not null default 0 check (repositories_total >= 0),
  repositories_today integer not null default 0 check (repositories_today >= 0),
  repositories_7_days integer not null default 0 check (repositories_7_days >= 0),
  repositories_14_days integer not null default 0 check (repositories_14_days >= 0),
  repositories_30_days integer not null default 0 check (repositories_30_days >= 0),

  detected_deployments integer not null default 0 check (detected_deployments >= 0),

  latest_repository text,
  last_activity text,
  status text not null default 'Pending',
  updated_at timestamptz not null default now(),

  constraint github_contribution_window_order check (
    contributions_today
    <= contributions_7_days
    and contributions_7_days
    <= contributions_14_days
    and contributions_14_days
    <= contributions_30_days
  ),

  constraint github_commit_window_order check (
    commits_today
    <= commits_7_days
    and commits_7_days
    <= commits_14_days
    and commits_14_days
    <= commits_30_days
  ),

  constraint github_repo_window_order check (
    repositories_today
    <= repositories_7_days
    and repositories_7_days
    <= repositories_14_days
    and repositories_14_days
    <= repositories_30_days
    and repositories_30_days
    <= repositories_total
  )
);

-- 3) One historical snapshot per student per date.
create table if not exists public.github_performance_history (
  id bigint generated by default as identity primary key,

  register_number text not null
    references public.students(register_number)
    on update cascade
    on delete cascade,

  snapshot_date date not null,
  section text not null,
  student_name text not null,
  github_username text,

  contributions_today integer not null default 0,
  contributions_7_days integer not null default 0,
  contributions_14_days integer not null default 0,
  contributions_30_days integer not null default 0,

  commits_today integer not null default 0,
  commits_7_days integer not null default 0,
  commits_14_days integer not null default 0,
  commits_30_days integer not null default 0,

  repositories_total integer not null default 0,
  repositories_today integer not null default 0,
  repositories_7_days integer not null default 0,
  repositories_14_days integer not null default 0,
  repositories_30_days integer not null default 0,

  detected_deployments integer not null default 0,

  latest_repository text,
  last_activity text,
  status text not null default 'Pending',
  updated_at timestamptz not null default now(),

  unique (register_number, snapshot_date)
);

create index if not exists github_history_snapshot_date_idx
on public.github_performance_history(snapshot_date desc);

create index if not exists github_history_section_idx
on public.github_performance_history(section, snapshot_date desc);

-- 4) RLS.
alter table public.github_performance_current enable row level security;
alter table public.github_performance_history enable row level security;

drop policy if exists "Public read GitHub current" on public.github_performance_current;
create policy "Public read GitHub current"
on public.github_performance_current
for select
to anon, authenticated
using (true);

drop policy if exists "Public read GitHub history" on public.github_performance_history;
create policy "Public read GitHub history"
on public.github_performance_history
for select
to anon, authenticated
using (true);

-- Writes are performed by the service-role tracker.
-- No anon/authenticated INSERT/UPDATE/DELETE policy is intentionally created.

-- 5) Helpful verification.
select
  'GitHub tracker schema ready' as status,
  count(*) as students
from public.students;
