-- Run this in Supabase SQL Editor on your EXISTING project.


-- ---------------------------------------------------------------------
-- FACULTY LEETCODE TRACKING
-- ---------------------------------------------------------------------
create table if not exists public.faculties (
  id bigint generated by default as identity primary key,
  faculty_id text not null unique,
  faculty_name text not null,
  designation text not null,
  department text not null default 'ECE',
  email text not null unique,
  leetcode_username text not null unique,
  total_solved integer not null default 0,
  easy integer not null default 0,
  medium integer not null default 0,
  hard integer not null default 0,
  total_submissions integer not null default 0,
  solved_today integer not null default 0,
  last_7_days integer not null default 0,
  last_30_days integer not null default 0,
  last_problem text,
  last_solved text,
  status text not null default 'Pending',
  tracked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.faculties
  add column if not exists leetcode_username text,
  add column if not exists total_solved integer not null default 0,
  add column if not exists easy integer not null default 0,
  add column if not exists medium integer not null default 0,
  add column if not exists hard integer not null default 0,
  add column if not exists total_submissions integer not null default 0,
  add column if not exists solved_today integer not null default 0,
  add column if not exists last_7_days integer not null default 0,
  add column if not exists last_30_days integer not null default 0,
  add column if not exists last_problem text,
  add column if not exists last_solved text,
  add column if not exists status text not null default 'Pending',
  add column if not exists tracked_at timestamptz;

create unique index if not exists faculties_leetcode_username_unique
on public.faculties(leetcode_username)
where leetcode_username is not null;

alter table public.faculties enable row level security;

drop policy if exists "Public can read faculties" on public.faculties;
create policy "Public can read faculties"
on public.faculties
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert faculties" on public.faculties;
create policy "Admin can insert faculties"
on public.faculties
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin can update faculties" on public.faculties;
create policy "Admin can update faculties"
on public.faculties
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin can delete faculties" on public.faculties;
create policy "Admin can delete faculties"
on public.faculties
for delete
to authenticated
using (public.is_admin());


select 'FACULTY LEETCODE TRACKING READY' as status;
