-- Run this in Supabase SQL Editor on your EXISTING project.


-- ---------------------------------------------------------------------
-- FACULTY DIRECTORY
-- ---------------------------------------------------------------------
create table if not exists public.faculties (
  id bigint generated by default as identity primary key,
  faculty_id text not null unique,
  faculty_name text not null,
  designation text not null,
  department text not null default 'ECE',
  email text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.faculties enable row level security;

drop policy if exists "Public can read faculties" on public.faculties;
create policy "Public can read faculties"
on public.faculties
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert faculties" on public.faculties;
create policy "Admin can insert faculties"
on public.faculties
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin can update faculties" on public.faculties;
create policy "Admin can update faculties"
on public.faculties
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin can delete faculties" on public.faculties;
create policy "Admin can delete faculties"
on public.faculties
for delete
to authenticated
using (public.is_admin());


select 'FACULTY SECTION READY' as status;
