-- =====================================================================
-- CODEMETRIX LEETCODE SYNC - EXTENSION STATE & BYPASS DETECTION
-- Run once in Supabase SQL Editor.
-- =====================================================================

-- 1. Ensure table exists
CREATE TABLE IF NOT EXISTS public.extension_installed_students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  register_number TEXT NOT NULL,
  student_name TEXT NOT NULL,
  section TEXT DEFAULT 'ECE',
  leetcode_username TEXT,
  extension_version TEXT DEFAULT '1.0.0',
  auto_sync_enabled BOOLEAN DEFAULT true,
  installed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_active_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Ensure columns & constraints
ALTER TABLE public.extension_installed_students 
  ADD COLUMN IF NOT EXISTS auto_sync_enabled BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS extension_version TEXT DEFAULT '1.0.0',
  ADD COLUMN IF NOT EXISTS installed_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE public.extension_installed_students DROP CONSTRAINT IF EXISTS uq_ext_inst_reg;
ALTER TABLE public.extension_installed_students ADD CONSTRAINT uq_ext_inst_reg UNIQUE (register_number);

-- 3. Indexes for fast heartbeat queries & status audits
CREATE INDEX IF NOT EXISTS idx_ext_inst_reg ON public.extension_installed_students(register_number);
CREATE INDEX IF NOT EXISTS idx_ext_inst_auto_sync ON public.extension_installed_students(auto_sync_enabled);
CREATE INDEX IF NOT EXISTS idx_ext_inst_last_active ON public.extension_installed_students(last_active_at DESC);

-- 4. RLS Security Policies
ALTER TABLE public.extension_installed_students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public to read extension installs" ON public.extension_installed_students;
DROP POLICY IF EXISTS "Allow extension to insert installs" ON public.extension_installed_students;
DROP POLICY IF EXISTS "Allow extension to update installs" ON public.extension_installed_students;

CREATE POLICY "Allow public to read extension installs"
ON public.extension_installed_students FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow extension to insert installs"
ON public.extension_installed_students FOR INSERT TO anon, authenticated
WITH CHECK (length(trim(register_number)) > 0);

CREATE POLICY "Allow extension to update installs"
ON public.extension_installed_students FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

-- 5. Drop old view completely to avoid column rename collision
DROP VIEW IF EXISTS public.extension_status_overview CASCADE;

-- 6. Recreate Live Extension State Overview View
CREATE VIEW public.extension_status_overview AS
SELECT 
  s.register_number,
  s.student_name,
  s.section,
  s.leetcode_username,
  e.extension_version,
  CASE 
    WHEN e.register_number IS NULL THEN '🔴 NOT_INSTALLED'
    WHEN e.auto_sync_enabled = false THEN '🔴 TURNED_OFF_IN_POPUP'
    WHEN e.last_active_at < (now() - interval '24 hours') THEN '🟡 DISABLED_OR_INACTIVE'
    ELSE '🟢 ACTIVE_AND_SYNCING'
  END AS extension_state,
  COALESCE(e.auto_sync_enabled, false) AS auto_sync_enabled,
  e.installed_at,
  e.last_active_at,
  ROUND(EXTRACT(EPOCH FROM (now() - e.last_active_at)) / 60) AS minutes_since_last_ping,
  COALESCE(sub_stats.total_synced_solutions, 0) AS total_synced_solutions,
  COALESCE(sub_stats.flagged_solutions, 0) AS flagged_solutions,
  COALESCE(sub_stats.today_synced_solutions, 0) AS today_synced_solutions
FROM public.students s
LEFT JOIN public.extension_installed_students e 
  ON s.register_number = e.register_number
LEFT JOIN (
  SELECT 
    register_number,
    COUNT(*) AS total_synced_solutions,
    COUNT(*) FILTER (WHERE plagiarism_verdict IN ('FLAGGED', 'SUSPICIOUS')) AS flagged_solutions,
    COUNT(*) FILTER (WHERE submitted_at >= (now() - interval '24 hours')) AS today_synced_solutions
  FROM public.student_leetcode_submissions
  GROUP BY register_number
) sub_stats 
  ON s.register_number = sub_stats.register_number
ORDER BY s.section, s.register_number;

GRANT SELECT ON public.extension_status_overview TO anon, authenticated;
