-- ============================================================
-- AI PERFORMANCE ANALYST UPGRADE
-- Run this ONCE in Supabase SQL Editor on your EXISTING project.
-- ============================================================


-- ---------------------------------------------------------------------
-- AI PERFORMANCE ANALYST DATA MART
-- Current + daily snapshot of deterministic tracker metrics.
-- The AI Edge Function reads these tables with the service-role key.
-- ---------------------------------------------------------------------
create table if not exists public.student_performance_current (
  register_number text primary key,
  student_name text not null,
  section text not null,
  leetcode_username text not null,
  total_solved integer not null default 0,
  solved_today integer not null default 0,
  last_7_days integer not null default 0,
  last_14_days integer not null default 0,
  last_30_days integer not null default 0,
  last_7_days_submissions integer not null default 0,
  total_submissions integer not null default 0,
  easy integer not null default 0,
  medium integer not null default 0,
  hard integer not null default 0,
  last_problem text,
  last_solved text,
  status text not null default 'Pending',
  overall_rank integer,
  section_rank integer,
  updated_at timestamptz not null default now()
);

create table if not exists public.student_performance_history (
  id bigint generated by default as identity primary key,
  register_number text not null,
  snapshot_date date not null,
  total_solved integer not null default 0,
  solved_today integer not null default 0,
  last_7_days integer not null default 0,
  last_14_days integer not null default 0,
  last_30_days integer not null default 0,
  last_7_days_submissions integer not null default 0,
  easy integer not null default 0,
  medium integer not null default 0,
  hard integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(register_number, snapshot_date)
);

create index if not exists idx_student_performance_current_section
on public.student_performance_current(section);

create index if not exists idx_student_performance_history_register_date
on public.student_performance_history(register_number, snapshot_date);

alter table public.student_performance_current enable row level security;
alter table public.student_performance_history enable row level security;

-- Only authenticated administrators may directly read these analytics tables.
-- The AI Edge Function uses service-role access and independently checks admin role.
drop policy if exists "Admin can read current performance" on public.student_performance_current;
create policy "Admin can read current performance"
on public.student_performance_current
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin can read performance history" on public.student_performance_history;
create policy "Admin can read performance history"
on public.student_performance_history
for select
to authenticated
using (public.is_admin());

select 'AI PERFORMANCE ANALYST DATABASE READY' as status;
