-- =====================================================================
-- CODEMETRIX LEETCODE SYNC - SUPABASE DATABASE MIGRATION
-- With 1-Email-1-Extension Lock, Deduplication, 50-Problem Rolling Limit,
-- and Section Advisors Registry for Automated Email Dispatch
-- =====================================================================

begin;

-- =====================================================================
-- 1. TABLE: public.student_leetcode_submissions
-- =====================================================================
create table if not exists public.student_leetcode_submissions (
  id bigint generated by default as identity primary key,
  register_number text not null,
  student_email text,
  leetcode_username text not null,
  problem_title text not null,
  problem_slug text not null,
  problem_difficulty text default 'Medium' check (problem_difficulty in ('Easy', 'Medium', 'Hard', 'Unknown')),
  language text not null,
  submission_status text not null default 'Accepted',
  runtime_ms integer default 0,
  runtime_percentile numeric default 0,
  memory_mb numeric default 0,
  memory_percentile numeric default 0,
  source_code text not null,
  
  -- Anti-Cheating & Forensics Telemetry
  keystrokes_count integer default 0,
  keystroke_ratio numeric default 0,
  is_pasted boolean default false,
  paste_count integer default 0,
  time_spent_seconds integer default 0,
  tab_switch_count integer default 0,
  has_prompt_comments boolean default false,
  ai_comment_flags text[] default '{}',
  plagiarism_risk_score integer default 0,
  plagiarism_verdict text default 'CLEAN' check (plagiarism_verdict in ('CLEAN', 'LOW_RISK', 'SUSPICIOUS', 'FLAGGED')),
  peer_similarity_pct numeric default 0,
  
  notes text,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Ensure all columns exist
alter table public.student_leetcode_submissions add column if not exists student_email text;
alter table public.student_leetcode_submissions add column if not exists keystrokes_count integer default 0;
alter table public.student_leetcode_submissions add column if not exists keystroke_ratio numeric default 0;
alter table public.student_leetcode_submissions add column if not exists is_pasted boolean default false;
alter table public.student_leetcode_submissions add column if not exists paste_count integer default 0;
alter table public.student_leetcode_submissions add column if not exists time_spent_seconds integer default 0;
alter table public.student_leetcode_submissions add column if not exists tab_switch_count integer default 0;
alter table public.student_leetcode_submissions add column if not exists has_prompt_comments boolean default false;
alter table public.student_leetcode_submissions add column if not exists ai_comment_flags text[] default '{}';
alter table public.student_leetcode_submissions add column if not exists plagiarism_risk_score integer default 0;
alter table public.student_leetcode_submissions add column if not exists plagiarism_verdict text default 'CLEAN';
alter table public.student_leetcode_submissions add column if not exists peer_similarity_pct numeric default 0;

-- Deduplication: Unique per (register_number, problem_slug) so resubmitting updates the latest code
alter table public.student_leetcode_submissions drop constraint if exists uq_student_submission;
alter table public.student_leetcode_submissions drop constraint if exists uq_student_problem;
alter table public.student_leetcode_submissions add constraint uq_student_problem unique (register_number, problem_slug);

-- Indexes
create index if not exists idx_submissions_register_number on public.student_leetcode_submissions(register_number);
create index if not exists idx_submissions_email on public.student_leetcode_submissions(student_email);
create index if not exists idx_submissions_submitted_at on public.student_leetcode_submissions(submitted_at desc);
create index if not exists idx_submissions_problem_slug on public.student_leetcode_submissions(problem_slug);
create index if not exists idx_submissions_language on public.student_leetcode_submissions(language);

-- =====================================================================
-- 2. TABLE: public.extension_installed_students (1 Email = 1 Extension Lock)
-- =====================================================================
create table if not exists public.extension_installed_students (
  id bigint generated by default as identity primary key,
  register_number text not null unique,
  student_email text not null unique,
  student_name text not null,
  section text default 'ECE',
  leetcode_username text,
  extension_version text default '1.0.0',
  auto_sync_enabled boolean default true,
  installed_at timestamptz not null default now(),
  last_active_at timestamptz not null default now()
);

-- Ensure columns & constraints
alter table public.extension_installed_students add column if not exists student_email text;
alter table public.extension_installed_students drop constraint if exists uq_ext_inst_reg;
alter table public.extension_installed_students drop constraint if exists uq_ext_inst_email;
alter table public.extension_installed_students add constraint uq_ext_inst_reg unique (register_number);
alter table public.extension_installed_students add constraint uq_ext_inst_email unique (student_email);

create index if not exists idx_ext_inst_reg on public.extension_installed_students(register_number);
create index if not exists idx_ext_inst_email on public.extension_installed_students(student_email);
create index if not exists idx_ext_inst_last_active on public.extension_installed_students(last_active_at desc);

-- =====================================================================
-- 3. TABLE: public.section_advisors (Section Advisor Email Registry)
-- =====================================================================
create table if not exists public.section_advisors (
  id bigint generated by default as identity primary key,
  section text not null unique,
  advisor_name text not null,
  advisor_email text not null,
  updated_at timestamptz not null default now()
);

-- Seed default section advisors (can be edited by admin in dashboard)
insert into public.section_advisors (section, advisor_name, advisor_email)
values
  ('ECE A', 'ECE A Advisor', 'advisor.ecea@bitsathy.ac.in'),
  ('ECE B', 'ECE B Advisor', 'advisor.eceb@bitsathy.ac.in'),
  ('ECE C', 'ECE C Advisor', 'advisor.ecec@bitsathy.ac.in'),
  ('ECE D', 'ECE D Advisor', 'advisor.eced@bitsathy.ac.in'),
  ('ECE E', 'ECE E Advisor', 'advisor.ecee@bitsathy.ac.in'),
  ('ECE F', 'ECE F Advisor', 'advisor.ecef@bitsathy.ac.in')
on conflict (section) do update
set advisor_name = excluded.advisor_name,
    advisor_email = excluded.advisor_email;

-- =====================================================================
-- 4. TRIGGER: Automatic Rolling 50 Submissions Limit per Student
-- =====================================================================
create or replace function public.prune_student_excess_submissions()
returns trigger
language plpgsql
security definer
as $$
declare
  v_count integer;
begin
  select count(*) into v_count
  from public.student_leetcode_submissions
  where register_number = new.register_number;

  if v_count > 50 then
    delete from public.student_leetcode_submissions
    where id in (
      select id from public.student_leetcode_submissions
      where register_number = new.register_number
      order by submitted_at asc
      limit (v_count - 50)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prune_submissions on public.student_leetcode_submissions;
create trigger trg_prune_submissions
after insert or update on public.student_leetcode_submissions
for each row execute function public.prune_student_excess_submissions();

-- =====================================================================
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================================
alter table public.student_leetcode_submissions enable row level security;
alter table public.extension_installed_students enable row level security;
alter table public.section_advisors enable row level security;

-- Submissions Policies
drop policy if exists "Allow public and authenticated to read submissions" on public.student_leetcode_submissions;
drop policy if exists "Allow public and extension to insert submissions" on public.student_leetcode_submissions;
drop policy if exists "Allow public and extension to update submissions" on public.student_leetcode_submissions;
drop policy if exists "Allow admins full access to submissions" on public.student_leetcode_submissions;

create policy "Allow public and authenticated to read submissions"
on public.student_leetcode_submissions for select to anon, authenticated using (true);

create policy "Allow public and extension to insert submissions"
on public.student_leetcode_submissions for insert to anon, authenticated
with check (length(trim(register_number)) > 0 and length(trim(problem_title)) > 0 and length(trim(source_code)) > 0);

create policy "Allow public and extension to update submissions"
on public.student_leetcode_submissions for update to anon, authenticated using (true) with check (true);

create policy "Allow admins full access to submissions"
on public.student_leetcode_submissions for all to authenticated
using (coalesce((select (auth.jwt() ->> 'role') = 'authenticated'), false));

-- Extension Installs Policies
drop policy if exists "Allow public to read extension installs" on public.extension_installed_students;
drop policy if exists "Allow extension to insert installs" on public.extension_installed_students;
drop policy if exists "Allow extension to update installs" on public.extension_installed_students;

create policy "Allow public to read extension installs"
on public.extension_installed_students for select to anon, authenticated using (true);

create policy "Allow extension to insert installs"
on public.extension_installed_students for insert to anon, authenticated
with check (length(trim(register_number)) > 0 and length(trim(student_name)) > 0);

create policy "Allow extension to update installs"
on public.extension_installed_students for update to anon, authenticated using (true) with check (true);

-- Section Advisors Policies
drop policy if exists "Allow public to read section advisors" on public.section_advisors;
drop policy if exists "Allow admins to update section advisors" on public.section_advisors;

create policy "Allow public to read section advisors"
on public.section_advisors for select to anon, authenticated using (true);

create policy "Allow admins to update section advisors"
on public.section_advisors for all to authenticated
using (coalesce((select (auth.jwt() ->> 'role') = 'authenticated'), false));

commit;
