-- ================================================================
-- ECE CodeMetrix - Student Profile Request Workflow
-- Run once in Supabase SQL Editor.
-- ================================================================

begin;

alter table public.students
  add column if not exists year integer,
  add column if not exists department text default 'ECE',
  add column if not exists leetcode_link text,
  add column if not exists github_username text,
  add column if not exists github_link text;

create unique index if not exists students_register_number_lower_unique
  on public.students (lower(btrim(register_number)));

create unique index if not exists students_github_username_unique
  on public.students (lower(btrim(github_username)))
  where github_username is not null and btrim(github_username) <> '';

create table if not exists public.profile_requests (
  id bigint generated by default as identity primary key,
  register_number text not null,
  student_name text not null,
  year integer not null check (year between 1 and 4),
  department text not null default 'ECE',
  section text not null,
  leetcode_username text not null,
  leetcode_link text not null,
  github_username text not null,
  github_link text not null,
  status text not null default 'Pending' check (status in ('Pending','Approved','Rejected')),
  requested_at timestamptz not null default now(),
  processed_at timestamptz,
  processed_by uuid references auth.users(id),
  admin_note text
);

create index if not exists profile_requests_status_idx on public.profile_requests(status, requested_at);
create index if not exists profile_requests_register_idx on public.profile_requests(lower(btrim(register_number)));

alter table public.profile_requests enable row level security;
drop policy if exists "Admins can read profile requests" on public.profile_requests;
create policy "Admins can read profile requests" on public.profile_requests for select to authenticated using (public.is_admin());
drop policy if exists "Admins can update profile requests" on public.profile_requests;
create policy "Admins can update profile requests" on public.profile_requests for update to authenticated using (public.is_admin()) with check (public.is_admin());

grant select, update on public.profile_requests to authenticated;


-- Public status RPC exposes only a small status response; it does not expose request records.
create or replace function public.get_profile_status(p_query text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q text := lower(btrim(coalesce(p_query,'')));
  s record;
  r record;
begin
  if q = '' then return jsonb_build_object('status','NOT_FOUND'); end if;
  select register_number, student_name into s
  from public.students
  where lower(btrim(register_number)) = q
     or lower(btrim(student_name)) = q
     or lower(coalesce(leetcode_username,'')) = q
     or lower(coalesce(github_username,'')) = q
  order by id
  limit 1;
  if found then return jsonb_build_object('status','ACTIVE','register_number',s.register_number,'student_name',s.student_name); end if;
  select register_number, student_name, status into r
  from public.profile_requests
  where lower(btrim(register_number)) = q
     or lower(btrim(student_name)) = q
     or lower(btrim(leetcode_username)) = q
     or lower(btrim(github_username)) = q
  order by requested_at desc limit 1;
  if found then return jsonb_build_object('status',upper(r.status),'register_number',r.register_number,'student_name',r.student_name); end if;
  return jsonb_build_object('status','NOT_FOUND');
end;
$$;
revoke all on function public.get_profile_status(text) from public;
grant execute on function public.get_profile_status(text) to anon, authenticated;

commit;
