-- Run ONCE in Supabase SQL Editor.
create table if not exists public.report_submission_snapshots (
  id bigint generated by default as identity primary key,
  register_number text not null,
  boundary_at timestamptz not null,
  total_submissions bigint not null default 0,
  created_at timestamptz not null default now(),
  constraint report_submission_snapshots_student_boundary_unique unique (register_number, boundary_at)
);
create index if not exists report_submission_snapshots_boundary_idx on public.report_submission_snapshots (boundary_at);
alter table public.report_submission_snapshots enable row level security;
