-- =====================================================================
-- ECE LEETCODE PLATFORM - FRESH SUPABASE SETUP
-- =====================================================================
-- FOR A BRAND-NEW SUPABASE PROJECT:
-- Run THIS ONE FILE in SQL Editor.
--
-- Creates:
--   students + admin roles
--   Daily Challenge
--   Daily Coding Test
--   one-attempt rule
--   coding analytics result fields
--   verification RPC
--   RLS policies
--
-- Safe to re-run for this schema.
-- =====================================================================

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- USERS / ADMIN ROLES
-- ---------------------------------------------------------------------
create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'public')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

drop policy if exists "Users can read own role" on public.user_roles;
create policy "Users can read own role"
on public.user_roles
for select
to authenticated
using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ---------------------------------------------------------------------
-- STUDENTS
-- ---------------------------------------------------------------------
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  register_number text not null unique,
  student_name text not null,
  leetcode_username text not null unique,
  section text not null default 'ECE E',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade older/fresh variants safely.
alter table public.students
  add column if not exists section text not null default 'ECE E',
  add column if not exists updated_at timestamptz not null default now();

alter table public.students enable row level security;

-- Remove policies from older project versions that allowed public profile writes.
drop policy if exists "Public can add students" on public.students;
drop policy if exists "Public can update students" on public.students;
drop policy if exists "Public can delete students" on public.students;

drop policy if exists "Public can read students" on public.students;
create policy "Public can read students"
on public.students
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert students" on public.students;
create policy "Admin can insert students"
on public.students
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin can update students" on public.students;
create policy "Admin can update students"
on public.students
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin can delete students" on public.students;
create policy "Admin can delete students"
on public.students
for delete
to authenticated
using (public.is_admin());


-- ---------------------------------------------------------------------
-- FACULTY LEETCODE TRACKING
-- ---------------------------------------------------------------------
create table if not exists public.faculties (
  id bigint generated by default as identity primary key,
  faculty_id text not null unique,
  faculty_name text not null,
  designation text not null,
  department text not null default 'ECE',
  email text not null unique,
  leetcode_username text not null unique,
  total_solved integer not null default 0,
  easy integer not null default 0,
  medium integer not null default 0,
  hard integer not null default 0,
  total_submissions integer not null default 0,
  solved_today integer not null default 0,
  last_7_days integer not null default 0,
  last_30_days integer not null default 0,
  last_problem text,
  last_solved text,
  status text not null default 'Pending',
  tracked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.faculties
  add column if not exists leetcode_username text,
  add column if not exists total_solved integer not null default 0,
  add column if not exists easy integer not null default 0,
  add column if not exists medium integer not null default 0,
  add column if not exists hard integer not null default 0,
  add column if not exists total_submissions integer not null default 0,
  add column if not exists solved_today integer not null default 0,
  add column if not exists last_7_days integer not null default 0,
  add column if not exists last_30_days integer not null default 0,
  add column if not exists last_problem text,
  add column if not exists last_solved text,
  add column if not exists status text not null default 'Pending',
  add column if not exists tracked_at timestamptz;

create unique index if not exists faculties_leetcode_username_unique
on public.faculties(leetcode_username)
where leetcode_username is not null;

alter table public.faculties enable row level security;

drop policy if exists "Public can read faculties" on public.faculties;
create policy "Public can read faculties"
on public.faculties
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert faculties" on public.faculties;
create policy "Admin can insert faculties"
on public.faculties
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admin can update faculties" on public.faculties;
create policy "Admin can update faculties"
on public.faculties
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admin can delete faculties" on public.faculties;
create policy "Admin can delete faculties"
on public.faculties
for delete
to authenticated
using (public.is_admin());

-- ---------------------------------------------------------------------
-- DAILY CHALLENGE
-- ---------------------------------------------------------------------
create table if not exists public.daily_challenges (
  id bigint generated by default as identity primary key,
  challenge_date date not null unique,
  problem_number integer,
  problem_title text not null,
  problem_slug text not null,
  problem_url text not null,
  difficulty text not null default 'Easy'
    check (difficulty in ('Easy', 'Medium', 'Hard')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_challenge_results (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null
    references public.daily_challenges(id) on delete cascade,
  register_number text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (challenge_id, register_number)
);

create index if not exists idx_daily_challenge_results_register
on public.daily_challenge_results(register_number);

alter table public.daily_challenges enable row level security;
alter table public.daily_challenge_results enable row level security;

drop policy if exists "Public can read daily challenges" on public.daily_challenges;
create policy "Public can read daily challenges"
on public.daily_challenges
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can manage daily challenges" on public.daily_challenges;
create policy "Admin can manage daily challenges"
on public.daily_challenges
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read challenge results" on public.daily_challenge_results;
create policy "Public can read challenge results"
on public.daily_challenge_results
for select
to anon, authenticated
using (true);

-- Result writes are performed by tracker.py using service-role.
-- No anonymous insert/update/delete policy is intentionally created.

-- ---------------------------------------------------------------------
-- DAILY CODING TEST
-- ---------------------------------------------------------------------
create table if not exists public.coding_tests (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  instructions text,
  duration_minutes integer not null check (duration_minutes > 0),
  total_marks numeric not null default 0,
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'closed')),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.coding_questions (
  id uuid primary key default gen_random_uuid(),
  test_id uuid not null
    references public.coding_tests(id) on delete cascade,
  question_number integer not null,
  title text not null,
  description text not null,
  difficulty text not null default 'Easy'
    check (difficulty in ('Easy', 'Medium', 'Hard')),
  marks numeric not null default 0,
  starter_code text,
  sample_input text,
  sample_output text,
  time_limit_ms integer not null default 3000,
  memory_limit_mb integer not null default 256,
  created_at timestamptz not null default now(),
  unique(test_id, question_number)
);

create table if not exists public.coding_test_cases (
  id bigint generated by default as identity primary key,
  question_id uuid not null
    references public.coding_questions(id) on delete cascade,
  input text,
  expected_output text not null,
  is_hidden boolean not null default true,
  marks numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.coding_attempts (
  id uuid primary key default gen_random_uuid(),
  test_id uuid not null
    references public.coding_tests(id) on delete cascade,
  register_number text not null,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  submitted_at timestamptz,
  status text not null default 'in_progress'
    check (status in ('in_progress', 'submitted', 'expired')),
  total_score numeric not null default 0,
  violation_count integer not null default 0,
  passed_cases integer not null default 0,
  total_cases integer not null default 0,
  result_status text
    check (result_status is null or result_status in ('passed', 'failed')),
  time_taken_seconds integer not null default 0,
  created_at timestamptz not null default now(),
  unique(test_id, register_number)
);

-- Upgrade old variants safely.
alter table public.coding_attempts
  add column if not exists passed_cases integer not null default 0,
  add column if not exists total_cases integer not null default 0,
  add column if not exists result_status text,
  add column if not exists time_taken_seconds integer not null default 0;

create unique index if not exists coding_attempts_one_attempt_per_student
on public.coding_attempts(test_id, register_number);

create index if not exists idx_coding_attempts_register
on public.coding_attempts(register_number);

create index if not exists idx_coding_attempts_test
on public.coding_attempts(test_id);

create index if not exists idx_coding_attempts_result
on public.coding_attempts(result_status);

create table if not exists public.coding_submissions (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null
    references public.coding_attempts(id) on delete cascade,
  question_id uuid not null
    references public.coding_questions(id) on delete cascade,
  source_code text not null default '',
  language text not null default 'java',
  passed_cases integer not null default 0,
  total_cases integer not null default 0,
  score numeric not null default 0,
  status text not null default 'draft',
  submitted_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(attempt_id, question_id)
);

create table if not exists public.coding_violations (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null
    references public.coding_attempts(id) on delete cascade,
  violation_type text not null,
  created_at timestamptz not null default now()
);

alter table public.coding_tests enable row level security;
alter table public.coding_questions enable row level security;
alter table public.coding_test_cases enable row level security;
alter table public.coding_attempts enable row level security;
alter table public.coding_submissions enable row level security;
alter table public.coding_violations enable row level security;

-- Published tests are public; admins can also see drafts/closed tests.
drop policy if exists "read published coding tests" on public.coding_tests;
create policy "read published coding tests"
on public.coding_tests
for select
to anon, authenticated
using (
  status = 'published'
  or public.is_admin()
);

drop policy if exists "read coding questions" on public.coding_questions;
create policy "read coding questions"
on public.coding_questions
for select
to anon, authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.coding_tests t
    where t.id = coding_questions.test_id
      and t.status = 'published'
  )
);

drop policy if exists "read visible coding cases" on public.coding_test_cases;
create policy "read visible coding cases"
on public.coding_test_cases
for select
to anon, authenticated
using (
  public.is_admin()
  or (
    is_hidden = false
    and exists (
      select 1
      from public.coding_questions q
      join public.coding_tests t on t.id = q.test_id
      where q.id = coding_test_cases.question_id
        and t.status = 'published'
    )
  )
);

drop policy if exists "admin manage coding tests" on public.coding_tests;
create policy "admin manage coding tests"
on public.coding_tests
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin manage coding questions" on public.coding_questions;
create policy "admin manage coding questions"
on public.coding_questions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin manage coding cases" on public.coding_test_cases;
create policy "admin manage coding cases"
on public.coding_test_cases
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Current register-number exam flow.
-- The unique (test_id, register_number) constraint enforces ONE attempt.
drop policy if exists "anon create attempts" on public.coding_attempts;
create policy "anon create attempts"
on public.coding_attempts
for insert
to anon
with check (true);

drop policy if exists "anon read attempts" on public.coding_attempts;
create policy "anon read attempts"
on public.coding_attempts
for select
to anon
using (true);

drop policy if exists "anon update attempts" on public.coding_attempts;
create policy "anon update attempts"
on public.coding_attempts
for update
to anon
using (true)
with check (true);

drop policy if exists "anon submissions" on public.coding_submissions;
create policy "anon submissions"
on public.coding_submissions
for all
to anon
using (true)
with check (true);

drop policy if exists "anon violations" on public.coding_violations;
create policy "anon violations"
on public.coding_violations
for insert
to anon
with check (true);

drop policy if exists "admin attempts" on public.coding_attempts;
create policy "admin attempts"
on public.coding_attempts
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin submissions" on public.coding_submissions;
create policy "admin submissions"
on public.coding_submissions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin violations" on public.coding_violations;
create policy "admin violations"
on public.coding_violations
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ---------------------------------------------------------------------
-- CODING TEST HELPERS
-- ---------------------------------------------------------------------
drop function if exists public.verify_coding_student(text);

create function public.verify_coding_student(
  p_register_number text
)
returns table(
  register_number text,
  student_name text,
  section text
)
language sql
security definer
set search_path = public
as $$
  select
    s.register_number::text,
    s.student_name::text,
    s.section::text
  from public.students s
  where btrim(s.register_number::text)
      = btrim(p_register_number)
  limit 1;
$$;

revoke all on function public.verify_coding_student(text) from public;
grant execute on function public.verify_coding_student(text)
to anon, authenticated;

create or replace function public.refresh_coding_test_marks()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_test_id uuid;
begin
  v_test_id := coalesce(new.test_id, old.test_id);

  update public.coding_tests
  set total_marks = coalesce(
    (
      select sum(marks)
      from public.coding_questions
      where test_id = v_test_id
    ),
    0
  )
  where id = v_test_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists coding_question_marks_refresh
on public.coding_questions;

create trigger coding_question_marks_refresh
after insert or update or delete
on public.coding_questions
for each row
execute function public.refresh_coding_test_marks();

commit;

select 'ECE LEETCODE FRESH SUPABASE SETUP READY' as status;
