-- ============================================================
-- FACULTY SAME-AS-STUDENT DASHBOARD UPGRADE
-- Run this ONCE in Supabase SQL Editor on the existing project.
-- ============================================================


-- ---------------------------------------------------------------------
-- FACULTY LEETCODE PROFILE HISTORY
-- Gives faculty profiles the same Progress + Daily Activity dashboards
-- as student profiles.
-- ---------------------------------------------------------------------
create table if not exists public.faculty_activity_history (
  id bigint generated by default as identity primary key,
  faculty_id bigint not null
    references public.faculties(id) on delete cascade,
  activity_date date not null,
  total_solved integer not null default 0,
  solved_today integer not null default 0,
  easy integer not null default 0,
  medium integer not null default 0,
  hard integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(faculty_id, activity_date)
);

create index if not exists idx_faculty_activity_history_faculty_date
on public.faculty_activity_history(faculty_id, activity_date);

alter table public.faculty_activity_history enable row level security;

drop policy if exists "Public can read faculty history"
on public.faculty_activity_history;

create policy "Public can read faculty history"
on public.faculty_activity_history
for select
to anon, authenticated
using (true);


select 'FACULTY SAME-AS-STUDENT DASHBOARD READY' as status;
