/**
 * CodeMetrix LeetCode Sync & Anti-Cheating Suite - Content Script
 * 
 * FEATURES:
 * 1. Keystroke Dynamics: Monaco editor typing events vs total character length.
 * 2. Active Tab Timing: Real-time tracking of active focus time on the problem tab.
 * 3. Clipboard & Paste Interception: Ctrl+V, Cmd+V, and right-click paste telemetry.
 * 4. AI Prompt Echo & Comment Scanner: Detects ChatGPT/Copilot comments, Complexity headers, Markdown fences.
 * 5. Composite Plagiarism Risk Scoring: Real-time calculation of risk score (0-100) & verdict.
 * 6. Strict Submit-Click-Only Trigger: Zero background sync; only fires upon explicit Submit button click.
 * 7. Single-Shot Mutex: Guarantees exactly one database insert per accepted submission.
 */

(function() {
  const DEFAULT_SUPABASE_URL = "https://bmbdkmtplemvlglqbgee.supabase.co";
  const DEFAULT_SUPABASE_ANON_KEY = "sb_publishable_mhASvZVhm997qjKiVb15LQ_MiLPXsRl";

  // STRICT USER-ACTION GATE & MUTEX
  let userJustClickedSubmit = false;
  let submitTimestamp = 0;
  let isCurrentlySyncing = false;

  // FORENSICS & TELEMETRY STATE
  let currentSlug = '';
  let keystrokesCount = 0;
  let isPasted = false;
  let pasteCount = 0;
  let problemStartTime = Date.now();
  let lastActiveTimestamp = Date.now();
  let accumulatedActiveSeconds = 0;
  let tabSwitchCount = 0;

  function isContextValid() {
    return typeof chrome !== 'undefined' && chrome.runtime && !!chrome.runtime.id;
  }

  // Reset telemetry counters whenever student switches to a new problem
  function resetForensicsIfProblemChanged() {
    const slug = getProblemSlug();
    if (slug && slug !== currentSlug) {
      currentSlug = slug;
      keystrokesCount = 0;
      isPasted = false;
      pasteCount = 0;
      problemStartTime = Date.now();
      lastActiveTimestamp = Date.now();
      accumulatedActiveSeconds = 0;
      tabSwitchCount = 0;
      console.log(`[CodeMetrix Forensics] Problem initialized: ${slug}`);
    }
  }

  // --- TAB ACTIVE TIME & VISIBILITY TRACKER ---
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'hidden') {
      const elapsed = (Date.now() - lastActiveTimestamp) / 1000;
      if (elapsed > 0) {
        accumulatedActiveSeconds += elapsed;
      }
      tabSwitchCount++;
    } else if (document.visibilityState === 'visible') {
      lastActiveTimestamp = Date.now();
    }
  });

  function getTotalActiveSeconds() {
    let total = accumulatedActiveSeconds;
    if (document.visibilityState === 'visible') {
      const currentSession = (Date.now() - lastActiveTimestamp) / 1000;
      if (currentSession > 0) total += currentSession;
    }
    return Math.max(1, Math.round(total));
  }

  // --- KEYSTROKE DYNAMICS LISTENER ---
  window.addEventListener('keydown', (e) => {
    resetForensicsIfProblemChanged();

    // Intercept Ctrl+V or Cmd+V
    if ((e.ctrlKey || e.metaKey) && (e.key === 'v' || e.key === 'V')) {
      isPasted = true;
      pasteCount++;
      console.log(`[CodeMetrix Forensics] Paste Shortcut Detected (Ctrl/Cmd+V). Total pastes: ${pasteCount}`);
      return;
    }

    // Filter out modifier & navigation-only keys from typing count
    const ignoredKeys = [
      'Shift', 'Control', 'Alt', 'Meta', 'CapsLock', 'Escape',
      'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight',
      'PageUp', 'PageDown', 'Home', 'End', 'Insert', 'F1', 'F2',
      'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12'
    ];

    if (!ignoredKeys.includes(e.key)) {
      keystrokesCount++;
    }
  }, true);

  // --- CLIPBOARD PASTE EVENT LISTENER ---
  window.addEventListener('paste', () => {
    resetForensicsIfProblemChanged();
    isPasted = true;
    pasteCount++;
    console.log(`[CodeMetrix Forensics] Clipboard Paste Event Detected. Total pastes: ${pasteCount}`);
  }, true);

  // --- AI PROMPT & COMMENT SIGNATURE SCANNER ---
  function scanAiComments(code) {
    if (!code) return { hasPromptComments: false, flags: [] };

    const flags = [];

    // 1. Time/Space Complexity AI summary headers
    const complexityRegex = /\b(time\s*complexity|space\s*complexity|time\s*:\s*o\(|space\s*:\s*o\(|complexity\s*analysis|runtime\s*complexity)\b/i;
    if (complexityRegex.test(code)) {
      flags.push('AI Complexity Header');
    }

    // 2. Direct ChatGPT / AI Assistant signatures
    const aiBrandRegex = /\b(chatgpt|copilot|claude|gemini|openai|gpt-4|anthropic|generated by ai|ai solution)\b/i;
    if (aiBrandRegex.test(code)) {
      flags.push('AI Brand Signature');
    }

    // 3. Prompt structured response artifacts (e.g., "Approach:", "Algorithm:", "Step 1:")
    const promptStructureRegex = /\b(approach|algorithm|step\s*1|explanation|intuition|dry\s*run)\s*:/i;
    if (promptStructureRegex.test(code)) {
      flags.push('AI Prompt Structure Artifact');
    }

    // 4. Markdown code fences (e.g. ```java or ``` pasted into Monaco)
    const markdownRegex = /```(?:java|cpp|c\+\+|python|python3|javascript|c|go|rust)?/i;
    if (markdownRegex.test(code)) {
      flags.push('Markdown Code Fence');
    }

    // 5. Verbatim problem prompt echo comments
    const promptEchoRegex = /\/\*\s*(?:Problem\s*Statement|Leetcode\s*#\s*\d+|Given\s+an\s+array|You\s+are\s+given)/i;
    const pyPromptEchoRegex = /#\s*(?:Problem\s*Statement|Leetcode\s*#\s*\d+|Given\s+an\s+array|You\s+are\s+given)/i;
    if (promptEchoRegex.test(code) || pyPromptEchoRegex.test(code)) {
      flags.push('Problem Prompt Echo Header');
    }

    return {
      hasPromptComments: flags.length > 0,
      flags: flags
    };
  }

  // --- COMPOSITE PLAGIARISM RISK SCORING ---
  function calculatePlagiarismRisk(code, difficulty, timeSpentSeconds, keystrokes, pasted, numPastes, switches, aiScanResult) {
    let score = 0;
    const finalFlags = [...(aiScanResult?.flags || [])];
    const codeLen = (code || '').trim().length;
    const ratio = codeLen > 0 ? (keystrokes / codeLen) : (keystrokes > 0 ? 1 : 0);
    const hasAiComments = Boolean(aiScanResult?.hasPromptComments);
    const hasPasteAction = Boolean(pasted || numPastes > 0);

    // DIRECT 100% FLAGGING RULES:
    // Rule 1: Any paste with minimal typing (< 40 keystrokes) OR low typed ratio (<= 20%)
    if (hasPasteAction && (keystrokes < 40 || ratio <= 0.20)) {
      score = 98;
      finalFlags.push(`Direct Code Paste Detected (${keystrokes} keys typed / ${numPastes} pastes / ${Math.round(ratio * 100)}% typed)`);
    }

    // Rule 2: 0% to 15% typing ratio on any substantive code
    if (ratio <= 0.15 && codeLen > 20) {
      score = Math.max(score, 95);
      finalFlags.push(`Extreme Keystroke Deficit (${keystrokes} Keystrokes for ${codeLen} chars, ${Math.round(ratio * 100)}% typed)`);
    }

    // Rule 3: Direct paste with keystrokes < 60
    if (hasPasteAction && keystrokes < 60) {
      score = Math.max(score, 90);
      finalFlags.push(`Pasted Code Insertion (${numPastes} pastes, ${keystrokes} keystrokes)`);
    }

    // Rule 4: AI Prompt signature / comments
    if (hasAiComments) {
      score = Math.max(score, (hasPasteAction || ratio < 0.5) ? 98 : 85);
      finalFlags.push('AI Generated Solution Signature / Header Comments');
    }

    // Rule 5: Low keystrokes (< 15) regardless of anything
    if (keystrokes < 15) {
      score = Math.max(score, 95);
      finalFlags.push(`Unverified / Low Keystroke Count (${keystrokes} keys)`);
    }

    // Secondary accumulative checks
    if (score < 80) {
      if (hasPasteAction && ratio < 0.35) {
        score += 45;
        finalFlags.push(`High Paste Ratio (${Math.round(ratio * 100)}% typed)`);
      } else if (ratio < 0.30) {
        score += 35;
        finalFlags.push('Low Typing Activity');
      }

      if (timeSpentSeconds < 20) {
        score += 30;
        finalFlags.push('Instant Solve Time (<20s)');
      }

      if (switches >= 3 && hasPasteAction) {
        score += 20;
        finalFlags.push(`Tab Switching Pre-Paste (${switches} switches)`);
      }
    }

    score = Math.min(100, Math.max(0, score));

    let verdict = 'CLEAN';
    if (score >= 70 || (hasPasteAction && keystrokes < 40) || ratio <= 0.15) {
      verdict = 'FLAGGED';
    } else if (score >= 45 || (hasPasteAction && ratio < 0.40)) {
      verdict = 'SUSPICIOUS';
    } else if (score >= 20) {
      verdict = 'LOW_RISK';
    }

    return {
      score: score,
      verdict: verdict,
      keystrokeRatio: parseFloat(ratio.toFixed(2)),
      flags: finalFlags,
      hasPromptComments: hasAiComments
    };
  }

  function showToast(title, message, isError = false, riskVerdict = '') {
    try {
      const existing = document.getElementById('codemetrix-toast');
      if (existing) existing.remove();

      const toast = document.createElement('div');
      toast.id = 'codemetrix-toast';
      if (isError) toast.className = 'error';

      let headerColor = isError ? '#f85149' : '#3fb950';
      let icon = isError ? '⚠️' : '⚡';

      if (riskVerdict === 'FLAGGED') {
        headerColor = '#f85149';
        icon = '🚨';
      } else if (riskVerdict === 'SUSPICIOUS') {
        headerColor = '#d29922';
        icon = '⚠️';
      }

      toast.innerHTML = `
        <div class="cm-icon">${icon}</div>
        <div class="cm-content">
          <h4 style="color: ${headerColor}">${title}</h4>
          <p>${message}</p>
        </div>
      `;

      document.body.appendChild(toast);

      setTimeout(() => {
        if (toast && toast.parentNode) {
          toast.style.transition = 'opacity 0.4s ease, transform 0.4s ease';
          toast.style.opacity = '0';
          toast.style.transform = 'translateX(120%)';
          setTimeout(() => toast.remove(), 400);
        }
      }, 5000);
    } catch (e) {}
  }

  function getProblemSlug() {
    const match = window.location.pathname.match(/\/problems\/([^\/]+)/);
    return match ? match[1] : '';
  }

  function getProblemTitle() {
    try {
      const titleEl = document.querySelector('div[class*="text-title-large"], a[href*="/problems/"], div[data-cy="question-title"], h4[class*="text-"]');
      if (titleEl && titleEl.textContent) {
        const text = titleEl.textContent.trim();
        if (text.length > 2 && !text.includes('LeetCode') && !text.includes('Problem List')) {
          return text;
        }
      }
    } catch (e) {}

    const slug = getProblemSlug();
    if (!slug) return 'LeetCode Problem';
    return slug
      .split('-')
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }

  function getProblemDifficulty() {
    try {
      const diffEl = document.querySelector(
        'div[class*="text-olive"], div[class*="text-yellow"], div[class*="text-pink"], ' +
        'div[class*="text-difficulty-"], div[class*="text-green"], div[class*="text-red"], ' +
        'span[class*="text-olive"], span[class*="text-yellow"], span[class*="text-pink"]'
      );

      if (diffEl && diffEl.textContent) {
        const txt = diffEl.textContent.trim().toLowerCase();
        if (txt.includes('easy')) return 'Easy';
        if (txt.includes('medium')) return 'Medium';
        if (txt.includes('hard')) return 'Hard';
      }

      const descArea = document.querySelector('div[data-track-load="description_content"], div[class*="description__"]');
      const fullText = (descArea ? descArea.parentElement.innerText : document.body.innerText) || '';
      const topChunk = fullText.slice(0, 1500);
      if (/\bEasy\b/i.test(topChunk)) return 'Easy';
      if (/\bHard\b/i.test(topChunk)) return 'Hard';
      if (/\bMedium\b/i.test(topChunk)) return 'Medium';
    } catch (e) {}

    return 'Easy';
  }

  function getSourceCode() {
    try {
      const lines = document.querySelectorAll('.monaco-editor .view-line');
      if (lines && lines.length > 0) {
        const codeArr = [];
        lines.forEach(l => codeArr.push(l.innerText || l.textContent || ''));
        const joined = codeArr.join('\n');
        if (joined.trim().length > 10) return joined;
      }
    } catch (e) {}

    try {
      const textareas = document.querySelectorAll('textarea');
      for (const t of textareas) {
        if (t.value && t.value.length > 20) return t.value;
      }
    } catch (e) {}

    return '';
  }

  function getActiveLanguage() {
    const knownLanguages = [
      'Java', 'C++', 'Python3', 'Python', 'C', 'C#', 'JavaScript',
      'TypeScript', 'Go', 'Rust', 'Kotlin', 'Swift', 'Ruby', 'PHP',
      'Dart', 'Scala', 'Racket', 'Erlang', 'Elixir', 'SQL', 'Pandas'
    ];

    try {
      const buttons = document.querySelectorAll('button');
      for (const btn of buttons) {
        const txt = (btn.textContent || '').trim();
        for (const lang of knownLanguages) {
          if (txt === lang || txt.startsWith(lang + ' ') || txt === lang.toLowerCase()) {
            return lang;
          }
        }
      }

      const langSelect = document.querySelector('[data-cy="lang-select"], button[id*="headlessui-listbox-button"]');
      if (langSelect && langSelect.textContent) {
        const txt = langSelect.textContent.trim();
        for (const lang of knownLanguages) {
          if (txt.includes(lang)) return lang;
        }
      }
    } catch (e) {}

    const code = getSourceCode();
    if (code) {
      if (code.includes('public class') || (code.includes('class Solution') && code.includes('public ') && code.includes(';')) || code.includes('System.out.')) {
        return 'Java';
      }
      if (code.includes('#include') || code.includes('std::') || code.includes('vector<') || code.includes('cout <<')) {
        return 'C++';
      }
      if (code.includes('def ') || code.includes('class Solution:') || code.includes('self,')) {
        return 'Python3';
      }
      if (code.includes('#include <stdio.h>') || code.includes('printf(')) {
        return 'C';
      }
      if (code.includes('function ') || code.includes('const ') || (code.includes('var ') && code.includes('=>'))) {
        return 'JavaScript';
      }
    }

    return 'Java';
  }

  function getLoggedLeetCodeUser() {
    try {
      const avatarLink = document.querySelector('a[href*="/u/"]');
      if (avatarLink) {
        const match = avatarLink.getAttribute('href').match(/\/u\/([^\/]+)/);
        if (match) return match[1];
      }
    } catch (e) {}
    return '';
  }

  async function syncAcceptedSubmission(submissionDetails) {
    if (isCurrentlySyncing) return;
    isCurrentlySyncing = true;

    if (!isContextValid()) {
      isCurrentlySyncing = false;
      return;
    }

    try {
      chrome.storage.local.get(['registerNumber', 'studentName', 'leetcodeUsername', 'autoSync', 'supabaseUrl', 'supabaseAnonKey'], async (config) => {
        if (!isContextValid()) {
          isCurrentlySyncing = false;
          return;
        }

        const regNumber = config.registerNumber;
        if (!regNumber) {
          showToast('CodeMetrix Setup Needed', 'Click the ⚡ extension icon in toolbar to enter your Register Number.', true);
          isCurrentlySyncing = false;
          return;
        }

        if (config.autoSync === false) {
          isCurrentlySyncing = false;
          return;
        }

        const supabaseUrl = config.supabaseUrl || DEFAULT_SUPABASE_URL;
        const supabaseKey = config.supabaseAnonKey || DEFAULT_SUPABASE_ANON_KEY;
        const lcUsername = config.leetcodeUsername || getLoggedLeetCodeUser() || regNumber;

        const problemTitle = submissionDetails.title || getProblemTitle();
        const problemSlug = submissionDetails.slug || getProblemSlug();
        const sourceCode = submissionDetails.code || getSourceCode();
        const language = submissionDetails.language || getActiveLanguage();
        const difficulty = submissionDetails.difficulty || getProblemDifficulty();

        // 1. FORENSICS ANALYSIS
        const activeTimeSecs = getTotalActiveSeconds();
        const aiScan = scanAiComments(sourceCode);
        const riskAnalysis = calculatePlagiarismRisk(
          sourceCode,
          difficulty,
          activeTimeSecs,
          keystrokesCount,
          isPasted,
          pasteCount,
          tabSwitchCount,
          aiScan
        );

        console.log('[CodeMetrix Forensics Report]', {
          keystrokes: keystrokesCount,
          isPasted: isPasted,
          pasteCount: pasteCount,
          activeTimeSeconds: activeTimeSecs,
          tabSwitches: tabSwitchCount,
          aiScan: aiScan,
          riskScore: riskAnalysis.score,
          verdict: riskAnalysis.verdict,
          flags: riskAnalysis.flags
        });

        // 2. SUPABASE PAYLOAD WITH FORENSICS
        const payload = {
          register_number: regNumber,
          leetcode_username: lcUsername,
          problem_title: problemTitle,
          problem_slug: problemSlug,
          problem_difficulty: difficulty,
          language: language,
          submission_status: 'Accepted',
          runtime_ms: submissionDetails.runtime_ms || 0,
          runtime_percentile: submissionDetails.runtime_percentile || 0,
          memory_mb: submissionDetails.memory_mb || 0,
          memory_percentile: submissionDetails.memory_percentile || 0,
          source_code: sourceCode || ("// Accepted solution for " + problemTitle),
          keystrokes_count: keystrokesCount,
          keystroke_ratio: riskAnalysis.keystrokeRatio,
          is_pasted: isPasted,
          paste_count: pasteCount,
          time_spent_seconds: activeTimeSecs,
          tab_switch_count: tabSwitchCount,
          has_prompt_comments: riskAnalysis.hasPromptComments,
          ai_comment_flags: riskAnalysis.flags,
          plagiarism_risk_score: riskAnalysis.score,
          plagiarism_verdict: riskAnalysis.verdict,
          submitted_at: new Date().toISOString()
        };

        try {
          const resp = await fetch(`${supabaseUrl}/rest/v1/student_leetcode_submissions?on_conflict=register_number,problem_slug`, {
            method: 'POST',
            headers: {
              'apikey': supabaseKey,
              'Authorization': `Bearer ${supabaseKey}`,
              'Content-Type': 'application/json',
              'Prefer': 'resolution=merge-duplicates,return=minimal'
            },
            body: JSON.stringify(payload)
          });

          if (resp.ok) {
            // Update student last active timestamp in background
            fetch(`${supabaseUrl}/rest/v1/extension_installed_students?register_number=eq.${encodeURIComponent(regNumber)}`, {
              method: 'PATCH',
              headers: {
                'apikey': supabaseKey,
                'Authorization': `Bearer ${supabaseKey}`,
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({ last_active_at: new Date().toISOString() })
            }).catch(() => {});
          }

          let toastTitle = '⚡ CodeMetrix Synced!';
          let toastMsg = `${problemTitle} (${difficulty} • ${language}) recorded.`;

          if (riskAnalysis.verdict === 'FLAGGED') {
            toastTitle = '🚨 CodeMetrix Synced [Review Flagged]';
            toastMsg = `${problemTitle} recorded. Forensics: High Plagiarism/AI Risk (${riskAnalysis.score}%).`;
          } else if (riskAnalysis.verdict === 'SUSPICIOUS') {
            toastTitle = '⚠️ CodeMetrix Synced [Under Review]';
            toastMsg = `${problemTitle} recorded. Forensics: Suspicious activity (${riskAnalysis.score}%).`;
          } else {
            toastMsg = `${problemTitle} (${difficulty} • ${language}) recorded. Integrity: Clean (100% Authentic).`;
          }

          showToast(toastTitle, toastMsg, false, riskAnalysis.verdict);
        } catch (err) {
          console.error('[CodeMetrix Database Sync Error]', err);
        } finally {
          setTimeout(() => {
            isCurrentlySyncing = false;
          }, 2000);
        }
      });
    } catch (e) {
      isCurrentlySyncing = false;
    }
  }

  // 1. LISTEN TO USER CLICKING "SUBMIT" BUTTON ONLY
  document.addEventListener('click', (e) => {
    resetForensicsIfProblemChanged();

    const target = e.target;
    if (!target) return;

    // Check if clicked element is or inside a Submit button
    const btn = target.closest('button[data-e2e-locator="console-submit-button"], button');
    if (btn) {
      const text = (btn.textContent || '').trim().toLowerCase();
      // Must be the Submit button, NOT Run button
      if (text === 'submit' || (text.includes('submit') && !text.includes('run'))) {
        userJustClickedSubmit = true;
        submitTimestamp = Date.now();
        console.log('[CodeMetrix] Submit button clicked. Listening for Accepted verdict...');

        // Auto-expire submit gate after 45s if no verdict received
        setTimeout(() => {
          userJustClickedSubmit = false;
        }, 45000);
      }
    }
  }, true);

  // 2. OBSERVE FOR ACCEPTED VERDICT ONLY AFTER A REAL SUBMIT CLICK
  function initStrictObserver() {
    resetForensicsIfProblemChanged();

    const observer = new MutationObserver(() => {
      // IF THE USER DID NOT CLICK SUBMIT IN THIS SESSION, DO NOTHING!
      if (!userJustClickedSubmit) {
        return;
      }

      // Check if within 45s of submit click
      if (Date.now() - submitTimestamp > 45000) {
        userJustClickedSubmit = false;
        return;
      }

      if (!isContextValid()) {
        observer.disconnect();
        return;
      }

      const resultContainer = document.querySelector('[data-e2e-locator="submission-result"], div[class*="result__"], div[class*="status__"]');
      const allText = (resultContainer ? resultContainer.innerText : document.body.innerText) || '';

      // Ignore failed states
      const isFailed = (
        allText.includes('Wrong Answer') ||
        allText.includes('Runtime Error') ||
        allText.includes('Time Limit Exceeded') ||
        allText.includes('Memory Limit Exceeded') ||
        allText.includes('Compile Error') ||
        allText.includes('Output Limit Exceeded') ||
        allText.includes('Internal Error')
      );

      if (isFailed) {
        console.log('[CodeMetrix] Submission failed. Not syncing.');
        userJustClickedSubmit = false; // Close gate
        return;
      }

      // Check for "Accepted" banner
      const hasAcceptedBanner = (
        (allText.includes('Accepted') && (allText.includes('Runtime') || allText.includes('Beats') || allText.includes('Memory'))) ||
        (document.querySelector('[data-e2e-locator="submission-result"]') && document.querySelector('[data-e2e-locator="submission-result"]').innerText.includes('Accepted'))
      );

      // Must have Accepted banner AND submit was initiated
      if (hasAcceptedBanner && userJustClickedSubmit) {
        const slug = getProblemSlug();
        if (!slug) return;

        const code = getSourceCode();
        if (!code || code.trim().length < 5) return;

        if (isCurrentlySyncing) return;

        // SHUT OFF GATE IMMEDIATELY (Guarantees exactly ONE execution per submit click)
        userJustClickedSubmit = false;

        let runtime = 0;
        let memory = 0;
        try {
          const rMatch = allText.match(/Runtime\s*[:\n]?\s*([\d\.]+)\s*ms/i);
          if (rMatch) runtime = parseInt(rMatch[1]);
          const mMatch = allText.match(/Memory\s*[:\n]?\s*([\d\.]+)\s*MB/i);
          if (mMatch) memory = parseFloat(mMatch[1]);
        } catch (e) {}

        const lang = getActiveLanguage();
        const diff = getProblemDifficulty();

        console.log('[CodeMetrix] Accepted verdict detected! Syncing solution with forensics...');

        syncAcceptedSubmission({
          slug: slug,
          title: getProblemTitle(),
          difficulty: diff,
          language: lang,
          code: code,
          runtime_ms: runtime,
          memory_mb: memory
        });
      }
    });

    observer.observe(document.body, { childList: true, subtree: true });
  }

  // --- EXTENSION LIVENESS & HEARTBEAT ENGINE ---
  function sendLivenessHeartbeat() {
    if (!isContextValid()) return;
    try {
      chrome.storage.local.get(['registerNumber', 'studentEmail', 'autoSync'], (data) => {
        const regNumber = data.registerNumber;
        if (!regNumber || data.autoSync === false) return;
        const supabaseUrl = DEFAULT_SUPABASE_URL;
        const supabaseKey = DEFAULT_SUPABASE_ANON_KEY;

        fetch(`${supabaseUrl}/rest/v1/extension_installed_students?register_number=eq.${encodeURIComponent(regNumber)}`, {
          method: 'PATCH',
          headers: {
            'apikey': supabaseKey,
            'Authorization': `Bearer ${supabaseKey}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            last_active_at: new Date().toISOString(),
            auto_sync_enabled: true
          })
        }).catch(() => {});
      });
    } catch (e) {}
  }

  function startHeartbeatEngine() {
    sendLivenessHeartbeat();
    // Ping every 15 minutes while active on problem tab
    setInterval(sendLivenessHeartbeat, 15 * 60 * 1000);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
      initStrictObserver();
      startHeartbeatEngine();
    });
  } else {
    initStrictObserver();
    startHeartbeatEngine();
  }

  console.log('⚡ CodeMetrix Anti-Cheating & LeetCode Sync Engine Active.');
})();


